name: "vprofile IAC"
on:
  push:
     branches:
        -main
        -stages
     paths:
        -terraorm/**
  pull_request:
    branches:
      -main
    paths:
       -terraform/**


env:
 # creidentials for deploying to AWS 
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}
 # S3 bucket for storing teraform state files
 BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
 # AWS region for deploying reources
 AWS_REGION: us-east-1
 EKS_CLUSTER: vprofie17-eks

jobs:
   terraform:
    name: "Apply terraform code chnages"
    runs-on: ubuntu-latest
    defaults:
      run:
       shell: bash
       working-directory: ./terraform

    steps:
     - name: checkout source code
       uses: action/checkout@v4
       
     - name: setup teraform with specified version on the runner 
       uses: hashicorp/setup-terraform@v2
       with:
        terraform_version: 1.1.7

       name: terraform init
       id: init
       run: terraform init -backend-config="bucket= $BUCKET_TF_STATE "
      
       name: terraform format
       id: fmt
       run: terraform fmt -check

       name: terraform validate
       id: validate
       run: teraaform validate


       name: terraform plan
       id: plan
       run: terraform plan -no-color -out planfile -input=false
       continues-on-error: true


       name: terraform plan status
       if: steps.plan.outcome == 'failure'
       run: exit 1      